legos_app/models.py
''' Create database models to represent tables '''
from legos_app import db
from flask_login import UserMixin

class LegoBrick(db.Model):
  '''Lego Brick Model '''
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(200), nullable=False)
  brick_id = db.Column(db.String(80), nullable=False)
  quantity = db.Column(db.Integer, nullable=False)
  photo_url = db.Column(db.String(300), nullable=False)

class LegoSet(db.Model):
  '''Lego Set Model '''
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(200), nullable=False)
  set_id = db.Column(db.String(80), nullable=False)
  photo_url = db.Column(db.String(300), nullable=False)

class User(UserMixin, db.Model):
    ''' User Model '''
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f'<User: {self.username}>'

legos_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError
from legos_app.models import LegoSet, LegoBrick

class LegoBrickForm(FlaskForm):
  ''' Form to create a Lego Brick '''
  name = StringField('Brick Name', validators=[DataRequired(), Length(min=3, max=80)])
  brick_id = StringField('Brick ID', validators=[DataRequired()])
  quantity = IntegerField('Quantity', validators=[DataRequired()])
  photo_url = StringField('Photo URL', validators=[DataRequired()])
  submit = SubmitField('Submit')

class LegoSetForm(FlaskForm):
  ''' Form to create a Lego Set '''
  name = StringField('Set Name', validators=[DataRequired(), Length(min=3, max=80)])
  set_id = StringField('Set ID', validators=[DataRequired()])
  photo_url = StringField('Photo URL', validators=[DataRequired()])
  submit = SubmitField('Submit')

legos_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from legos_app.config import Config

import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

###########################
# Authentication
###########################

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from .models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

bcrypt = Bcrypt(app)

###########################
# Blueprints
###########################

from legos_app.main.routes import main
app.register_blueprint(main)

from legos_app.auth.routes import auth
app.register_blueprint(auth)

with app.app_context():
    db.create_all()

legos_app/main/routes.py
''' Import packages and modules '''
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user

from legos_app.models import User, LegoBrick, LegoSet
from legos_app.main.forms import LegoBrickForm, LegoSetForm
from legos_app import bcrypt

# Import app and db from events_app package so that we can run app
from legos_app import app, db

main = Blueprint("main", __name__)


############################################################
# MAIN ROUTES
############################################################

@main.route('/about')
def about():
  return render_template('about.html')

@main.route('/')
def homepage():
    '''Homepage route'''
    return render_template('index.html')

@main.route('/sets')
@login_required
def sets():
  set_list = LegoSet.query.all()
  return render_template('sets.html', set_list=set_list)

@main.route('/bricks')
@login_required
def bricks():
  form = LegoBrickForm()
  brick_list = LegoBrick.query.all()
  return render_template('bricks.html', brick_list=brick_list, form=form)

############################################################
# DATABASE ROUTES (currently only modifies bricks-list)
############################################################

@main.route('/bricks/add', methods=['GET', 'POST'])
@login_required
def add_brick():
    """Route to create and add a LEGO brick to the user's collection"""
    form = LegoBrickForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_brick = LegoBrick(
          name=form.name.data,
          brick_id=form.brick_id.data,
          quantity=form.quantity.data,
          photo_url=form.photo_url.data,
        )
        db.session.add(new_brick)
        db.session.commit()
        # redirects to bricks.html (our user's database)
        return redirect(url_for("main.bricks"))
    # returns add-brick form
    return render_template('add-brick.html', form=form)

@main.route('/bricks/delete/<lego_id>', methods=['POST'])
@login_required
def delete(lego_id):
    """ Deletes lego """

    item = LegoBrick.query.get(lego_id)
    db.session.delete(item)
    db.session.commit()
    # redirects to bricks.html (our user's database)
    return redirect(url_for("main.bricks"))

@main.route('/bricks/update/<lego_id>', methods=['POST'])
@login_required
def update(lego_id):
  """ Updates lego """

  # currently only updates one lego brick at a time (for if we want individual update buttons)
  item = LegoBrick.query.get(lego_id)
  form = LegoBrickForm(obj=item)
  
  form.populate_obj(item)
  db.session.add(item)
  db.session.commit()

  # redirects to bricks.html (our user's database)
  return redirect(url_for("main.bricks"))

if __name__ == '__main__':
  app.run(debug=True)

@main.route('/sets/add', methods=['GET', 'POST'])
@login_required
def add_set():
    """Route to create and add a LEGO set to the user's collection"""
    form = LegoSetForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_set = LegoSet(
          name=form.name.data,
          set_id=form.set_id.data,
          photo_url=form.photo_url.data,
        )
        db.session.add(new_set)
        db.session.commit()
        # redirects to .html (our user's database)
        return redirect(url_for("main.sets"))
    # returns add-set form
    return render_template('add-set.html', form=form)

@main.route('/sets/delete/<lego_set_id>', methods=['POST'])
@login_required
def delete_set(lego_set_id):
    """ Deletes set """

    set_item = LegoSet.query.get(lego_set_id)
    db.session.delete(set_item)
    db.session.commit()
    # redirects to sets.html (our user's database)
    return redirect(url_for("main.sets"))

if __name__ == '__main__':
  app.run(debug=True)

legos_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="../static/about.css">
<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />

<main>
<div class="ct-pageWrapper" id="ct-js-wrapper">
<section class="company-heading intro-type" id="parallax-one">
   <div class="container">
      <div class="row product-title-info">
         <div class="col-md-12">
            <h1>
               About Us
            </h1>
         </div>
      </div>
   </div>
   <div class="parallax" id="parallax-cta" style="background-image:url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pieces-of-lego-displayed-during-the-exhibition-at-alexandra-news-photo-1586272389.jpg);">
      &nbsp;
   </div>
</section>
<section class="story-section company-sections ct-u-paddingBoth100 paddingBothHalf noTopMobilePadding" id="section">
   <div class="container text-center">
      <h2>
         Lego Project
      </h2>
         <div class="red-border">
            &nbsp;
         </div>
         <p class="ct-u-size22 ct-u-fontWeight300 marginTop40">
            This website mainly focuses on it’s consists of a sort of LEGO package conversion unit. It's where one can provide a list of lego components, send it to the LEGO and have it send back sets one can create for the lego product. 
         </p>
      </div>
   </div>
</section>
</div>
</main>


{% endblock %}

legos_app/templates/add-brick.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />

<main>
    <h1 style="text-align: center">NEW BRICK</h1>
    <form method="POST" action="{{ url_for('main.add_brick') }}">
      {{ form.csrf_token }}
      <fieldset>
        <legend style="text-align: center">PLEASE FILL OUT YOUR BRICK INFORMATION</legend>

        <div class="container">
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.name.label }} 
              </div>
              {{ form.name }}
              <ul>
                {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.brick_id.label }} 
              </div>
              {{ form.brick_id }}
              <ul>
                {% for error in form.brick_id.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.quantity.label }} 
              </div>
              {{ form.quantity }}
              <ul>
                {% for error in form.quantity.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.photo_url.label }} 
              </div>
              {{ form.photo_url }}
              <ul>
                {% for error in form.photo_url.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div id="brickButton"style="text-align: center" class="row">
            <div class="col">
              {{ form.submit }}
            </div>
          </div>
        </div> 
      </fieldset>
    </form>
</main>

{% endblock content %}

legos_app/templates/add-set.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />

<main>
    <h1 style="text-align: center">NEW SET</h1>
    <form method="POST" action="{{ url_for('main.add_set') }}">
      {{ form.csrf_token }}
      <fieldset>
        <legend style="text-align: center">PLEASE FILL OUT YOUR SET INFORMATION</legend>
    
        <div class="container">
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.name.label }} 
              </div>
              {{ form.name }}
              <ul>
                {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.set_id.label }} 
              </div>
              {{ form.set_id }}
              <ul>
                {% for error in form.set_id.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.photo_url.label }} 
              </div>
              {{ form.photo_url }}
              <ul>
                {% for error in form.photo_url.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div id="submit-button"style="text-align: center" class="row">
            <div class="col">
              {{ form.submit }}
            </div>
          </div>
        </div>
      </fieldset>
    </form>
</main>

{% endblock content %}

legos_app/templates/add.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='bricks.css') }}" />

<main>
    <h1>New Brick</h1>
    <form method="POST" action="{{ url_for('main.add') }}">
      {{ form.csrf_token }}
      <fieldset>
        <legend>Please fill out your Bricks info:</legend>
    
        {{ form.name.label }} {{ form.name }}
        <ul>
          {% for error in form.name.errors %}
          <li class="error">{{ error }}</li>
          {% endfor %}
        </ul>
    
        {{ form.brick_id.label }} {{ form.brick_id }}
        <ul>
          {% for error in form.brick_id.errors %}
          <li class="error">{{ error }}</li>
          {% endfor %}
        </ul>

        {{ form.quantity.label }} {{ form.quantity }}
        <ul>
          {% for error in form.quantity.errors %}
          <li class="error">{{ error }}</li>
          {% endfor %}
        </ul>

        {{ form.photo_url.label }} {{ form.photo_url }}
        <ul>
          {% for error in form.photo_url.errors %}
          <li class="error">{{ error }}</li>
          {% endfor %}
        </ul>
    
        {{ form.submit }}
      </fieldset>
    </form>
</main>

{% endblock content %}

legos_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>LEGO</title>

    <!-- BOOTSTRAP THEME -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.min.css') }}"
    />
  </head>
  <body class="d-flex flex-column min-vh-100">
    <div class="flex-fill">
      <!-- NAVBAR -->
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/"
          ><img
            height="35"
            width="35"
            class="aem--svgImg"
            src="{{ url_for('static', filename='images/Lego-logo.jpg') }}"
            title="LEGO-Logo"
            alt="Startseite"
        /></a>

        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarColor01"
          aria-controls="navbarColor01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/"
                >HOME<span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">ABOUT</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/sets">SETS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/bricks">BRICKS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout">LOGOUT</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">LOGIN</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">SIGN UP</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      {% block content %}{% endblock %}

      <!-- FOOTER -->
      <div class="p-5 text-black">
        <a class="navbar-brand" href="/"
          ><img
            height="35"
            width="35"
            class="aem--svgImg"
            src="{{ url_for('static', filename='images/Lego-logo.jpg') }}"
            title="LEGO-Logo"
            alt="Startseite"
        /></a>
        ©2020 The LEGO Group. All rights reserved. Use of this site signifies
        your agreement to the terms of use.
      </div>

      <!-- CUSTOM SCRIPTS -->
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>

      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>

      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>

      <script src="../static/scripts.js"></script>
    </div>
  </body>
</html>

legos_app/templates/bricks.html
{% extends 'base.html' %}{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='bricks.css') }}" />

<main>
  <h1 class="my-5" style="text-align: center">LEGO BRICKS</h1>

  <div class="row ml-5 pl-5">
    <!-- Dynamic code to display all bricks -->
    {% for brick in brick_list %}
    <div class="col-lg-5 offset-lg-1">
      <img src="{{ brick.photo_url }}" class="img-fluid rounded" width="60" height="60"/>
      <h3>{{ brick.name }}</h3>
      <div class="row">
        <form method="POST" action="{{ url_for('main.update', lego_id=brick.id) }}">
          {{ form.csrf_token }}
          <fieldset>

              {{ form.quantity.label }}
              {{ form.quantity(value=brick.quantity) }}
                  
              <input type="submit" value="SAVE" class="btn btn-primary">
              
          </fieldset>
        </form>
        <form class="mx-2" method="POST" action="{{ url_for('main.delete', lego_id=brick.id) }}">
          <input type="submit" value="REMOVE" class="btn btn-primary">
        </form>
      </div>
      
    </div>
    {% endfor %}

  </div>

  <div class="jumbotron text-center mb-0">
    <a href="/bricks/add" class="btn btn-primary">ADD ITEM</a>
  </div>
</main>

{% endblock %}

legos_app/templates/index.html
{% extends 'base.html' %} {% block content %}

<link rel="stylesheet" href="../static/styles.css" />
<main>
  <!-- CAROUSEL -->
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img
          class="d-block w-100"
          src="{{ url_for('static', filename='images/lego-san-francisco.jpeg') }}"
          alt="1 slide"
        />
        <div class="carousel-caption d-none d-md-block"></div>
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="{{ url_for('static', filename='images/lego-bugatti-chiron.jpeg') }}"
          alt="2 slide"
        />
        <div class="carousel-caption d-none d-md-block"></div>
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="{{ url_for('static', filename='images/lego-the-beatles.jpeg') }}"
          alt="3 slide"
        />
        <div class="carousel-caption d-none d-md-block"></div>
      </div>
    </div>
    <a
      class="carousel-control-prev"
      href="#carouselExampleControls"
      role="button"
      data-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a
      class="carousel-control-next"
      href="#carouselExampleControls"
      role="button"
      data-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <!-- IMAGE -->
  <div class="hero-background-img"></div>

  <!-- VIDEO -->
  <div class="embed-responsive embed-responsive-16by9">
    <iframe
      class="embed-responsive-item"
      src="https://www.youtube.com/embed/NnTIXiYWyFs"
      allowfullscreen
    ></iframe>
  </div>

  <!-- CARDS -->
  <div class="container pb-5px pt-5px">
    <div class="row">
      <div class="col-lg-4">
        <img
          src="{{ url_for('static', filename='images/lego-art-1.jpg') }}"
          class="img-fluid rounded"
        />
        <h3>Star Wars™ The Sith™</h3>
        <p class="lead">
          Embrace your creative side with exclusive, never-before-seen images
          every Star Wars™ fan will love to build and display. Based on
          brand-new artwork created especially for LEGO® Art, Darth Maul™, Darth
          Vader™ and Kylo Ren™ are brought to life in three powerful color
          portraits.
        </p>
      </div>

      <div class="col-lg-4">
        <img
          src="{{ url_for('static', filename='images/lego-art-2.jpg') }}"
          class="img-fluid rounded"
        />
        <h3>Harry Potter™ Hogwarts™ Crests</h3>
        <p class="lead">
          Be you brave, wise, kind or cunning, there’s a house for you at
          Hogwarts™. And now, with this spellbinding, 4,249-piece set, you can
          proudly display your allegiance by recreating these original Hogwarts
          House crest designs.
        </p>
      </div>

      <div class="col-lg-4">
        <img
          src="{{ url_for('static', filename='images/lego-art-3.jpg') }}"
          class="img-fluid rounded"
        />
        <h3>Disney’s Mickey Mouse</h3>
        <p class="lead">
          Mickey Mouse is the ultimate definition of an icon. His influence on
          popular culture is matched perhaps only by his beloved Minnie Mouse.
          Luckily for us, both of these pocket-sized superstars can be recreated
          in this most-definitely-not-pocket-sized, 2,658-piece wall-art set!
        </p>
      </div>
    </div>
  </div>

<!-- CALL TO ACTION -->
{% if not current_user.is_authenticated %}
<div class="jumbotron text-center mb-0">
  <a href="/login" class="btn btn-primary">LOGIN INTO YOUR ACCOUNT</a>
</div>
{% endif %}
</main>

{% endblock %}

legos_app/templates/login.html
{% extends 'base.html' %} {% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />
<div class="d-flex flex-column min-vh-100">
  <div class="flex-fill">
    <h1 style="text-align: center">LOG IN</h1>

    <form action="/login" method="POST">
      {{ form.csrf_token }}
      <fieldset>
        <legend style="text-align: center">PLEASE ENTER YOUR CREDENTIALS</legend>

        <div class="container">
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.username.label }} 
              </div>
              {{ form.username }}
              <ul>
                {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.password.label }} 
              </div>
              {{ form.password }}
              <ul>
                {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              {{ form.submit }}
            </div>
          </div>        
      </fieldset>
    </form>
  </div>
</div>

{% endblock %}

legos_app/templates/sets.html
{% extends 'base.html' %}{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='sets.css') }}" />

<!-- THE FOOTER BREAKS WHEN A ROW OF 3 SETS ARE NOT CREATED -->

<main>

  <h1 class="my-5" style="text-align: center">LEGO SETS</h1>
  <div class="row">
    <div id="architecture"></div>

    <!-- Dynamic code to display all sets -->
    {% for set in set_list %}
    <div class="col-lg-4" style="text-align: center">
      <img src="{{ set.photo_url }}" width="300" height="300"/>
      <h3>{{set.name}}</h3>
      <!-- Removed set instruction functionality -->
      <!-- <a href="{{set.instructions_url}}" class="btn btn-primary">SEE BUILDING INSTRUCTIONS</a> -->
      <form method="POST" action="{{ url_for('main.delete_set', lego_set_id=set.id) }}" >
        <input type="submit" value="REMOVE" class="btn btn-primary" />
      </form>
    </div>
    {% endfor %}
  </div>
  <div class="jumbotron text-center mb-0">
    <a href="/sets/add" class="btn btn-primary">ADD ITEM</a>
  </div>
</main>

{% endblock %}

legos_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />
<div class="d-flex flex-column min-vh-100">
  <div class="flex-fill">
    <h1 style="text-align: center">SIGN UP</h1>

    <form action="/signup" method="POST">
      {{ form.csrf_token }}
      <fieldset>
        <legend style="text-align: center">PLEASE ENTER YOUR CREDENTIALS</legend>

        <div class="container">
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.username.label }}
              </div>
              {{ form.username }}
              <ul>
              {% for error in form.username.errors %}
                  <li class="error">{{ error }}</li>
              {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              <div>
                {{ form.password.label }}
              </div>
              {{ form.password }}
              <ul>
                {% for error in form.password.errors %}
                    <li class="error">{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div style="text-align: center" class="row">
            <div class="col">
              {{ form.submit }}
            </div>
          </div>
      </fieldset>
    </form>
  </div>
</div>

{% endblock %}